### ISSUE TITLE
signature-pad in flutter

### ISSUE THREAD

**Issue by rafaeldl** [apptreesoftware/signature-pad-dart#1]
Hello,

is possible to use your signature-pad with flutter.io ?

**Comment by johnpryan** [comment]
Not yet, but this would be very easy to port to Flutter.  The two types imported from dart:html are Canvas and CanvasRenderingContext2d, so those would need to be factored out and given Fluter equivalents.  The rest of the bezier curve stuff is portable.

**Comment by rafaeldl** [comment]
Thanks a lot.. I'll try development.
