### ISSUE TITLE
[Feature] SVG export for the flutter version

### ISSUE THREAD

**Issue by masseelch** [apptreesoftware/signature-pad-dart#3]
I see the web version has an svg export.

Can we have the same for flutter? 

If you can provide some ideas / steps to go i am happy to help with a PR (if i can).

Regards

**Comment by johnpryan** [comment]
I'm not currently aware of a way to convert a dart:ui Canvas to an SVG, but you're welcome to do some research and see if it's possible!

For reference, here's code that turns the canvas into a PNG: https://github.com/apptreesoftware/signature-pad-dart/blob/master/signature_pad_flutter/lib/src/painter.dart#L55

**Comment by masseelch** [comment]
You are right. I could not find anything to make this happen. I'll stick to the png. Thanks!
